---
- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - nsxanswer.yml

  tasks:
  - name: Create SSH DNAT rule
    nsx_edge_nat:
      nsxmanager_spec: '{{ nsxmanager_spec }}'
      mode: 'create'
      name: '{{ edge_name }}'
      rule_type: 'dnat'
      vnic: '0'
      protocol: 'tcp'
      originalAddress: '10.0.0.1'
      originalPort: '22'
      translatedAddress: '192.168.0.2'
      translatedPort: '22'

  - name: Create default outbound SNAT rule
    nsx_edge_nat:
      nsxmanager_spec: '{{ nsxmanager_spec }}'
      mode: 'create'
      name: '{{ edge_name }}'
      rule_type: 'snat'
      vnic: '0'
      protocol: 'any'
      originalAddress: '192.168.0.0/20'
      originalPort: 'any'
      translatedAddress: '10.0.0.1'
      translatedPort: 'any'
